# Generated by Django 4.0.4 on 2022-06-06 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familiares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('edad', models.FloatField()),
                ('fecha_nacimiento', models.CharField(max_length=20)),
                ('parentesco', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
    ]
